### ISSUE TITLE
Peer to Peer code Review

### ISSUE THREAD

**Issue by Ali-0111** [ClintonYounge/Leaderboard-Project#3]
https://github.com/ClintonYounge/Leaderboard-Project/blob/f136af181961bf08566a83f5badd6e00023afae1/src/index.html#L9-L11

Hi @ClintonYounge 

You're making excellent progress with your HTML code! I can tell that you've been putting a lot of effort into it. In order to further enhance the organization and structure of your code, I have a suggestion that could be helpful.

## Required Issues to be worked on :recycle:
- [ ]  It would be beneficial to utilize the `<header>`  and include the h1 tag within it for better semantic organization. This will not only make your code more semantically sound, but it will also give it a more polished and professional look. For more information and guidance on HTML semantics, please refer to this helpful [resource](https://www.w3schools.com/html/html5_semantic_elements.asp)
Keep up the great work, and I have no doubt that your HTML code will be amazing! 😊 

_I always appreciate hearing from you. please do not forget to tag, so I can receive a notification._

**Comment by ClintonYounge** [comment]
Thank you for the review!
